name: admin

on:
  pull_request:
    branches: [dev]
    types: [opened]

defaults:
  run:
    working-directory: ./Admin/Sources

jobs:
  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name:
          Build and push Docker images
          # You may pin to the exact commit or the version.
          # uses: docker/build-push-action@9379083e426e2e84abb80c8c091f5cdeb7d3fd7a
        uses: docker/build-push-action@v2.3.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: ./Admin/Sources
          # Path to the Dockerfile
          file: ./Admin/Sources/Dockerfile
          # List of tags
          tags: somka4docker/citylogia-admin:latest
          # Push is a shorthand for --output=type=registry
          push: true
